services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    networks:
      - db
    volumes:
      - db:/var/lib/pgsql/data
    ports:
      - "5156:5432"

  asset:
    image: financeProj/asset
    build:
      context: src/AssetService
      dockerfile: DockerFile
    networks:
      - db
    ports:
      - "5159:8080"
    depends_on:
      - db

  finance-app:
    image: financeProj/finance-app
    build:
      context: src/FinanceApp
      dockerfile: DockerFile
    networks:
      - db
    ports:
      - "80:8080"
    depends_on:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
